# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/samib/Desktop/Master 1/AEO/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/my_ram/my_ram.xci
# IP: The module: 'my_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/samib/Desktop/Master 1/AEO/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/my_ram/my_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/samib/Desktop/Master 1/AEO/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/my_ram/my_ram.xci
# IP: The module: 'my_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/samib/Desktop/Master 1/AEO/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/my_ram/my_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
