#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 04 18:43:24 CET 2018
# SW Build 2288692 on Thu Jul 26 18:23:50 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim IP_fibo_behav -key {Behavioral:sim_1:Functional:IP_fibo} -tclbatch IP_fibo.tcl -view /home/m1/barchid/Desktop/AEO/TP_09/Basys3V6.srcs/sim_1/imports/nexys3V6_vivado/masterbench_behav.wcfg -log simulate.log
