# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer.xci
# IP: The module: 'timer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer.xci
# IP: The module: 'timer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/m1/slimani/Desktop/AEO/Basys3V6/Basys3V6.srcs/sources_1/ip/timer/timer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
