webtalk_init -webtalk_dir /home/l3/nowakowski/Desktop/TP01_BARCHID_SLIMANI/TP01_BARCHID_SLIMANI.sim/sim_1/behav/xsim/xsim.dir/toplevel_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 18 19:08:17 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1561681d-ed54-49cb-9226-72cb62f2c209" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b9b128d83254da08a45ce3f82c293e0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3658.320 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2230534725 -regid "" -xml /home/l3/nowakowski/Desktop/TP01_BARCHID_SLIMANI/TP01_BARCHID_SLIMANI.sim/sim_1/behav/xsim/xsim.dir/toplevel_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/l3/nowakowski/Desktop/TP01_BARCHID_SLIMANI/TP01_BARCHID_SLIMANI.sim/sim_1/behav/xsim/xsim.dir/toplevel_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/l3/nowakowski/Desktop/TP01_BARCHID_SLIMANI/TP01_BARCHID_SLIMANI.sim/sim_1/behav/xsim/xsim.dir/toplevel_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
